# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'trinitywizardtest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for trinitywizardtest

  target 'trinitywizardtestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'trinitywizardtestUITests' do
    # Pods for testing
  end

end
